#!/usr/bin/env node
// Generate src/js/card_data_uris.js from src/assets/cards/*.png
// Run automatically via `npm run prebuild` before electron-builder

const fs = require('fs');
const path = require('path');

const CARDS_DIR = path.join(__dirname, '..', 'src', 'assets', 'cards');
const OUT_PATH = path.join(__dirname, '..', 'src', 'js', 'card_data_uris.js');

const cards = {};
const files = fs.readdirSync(CARDS_DIR).sort();
for (const f of files) {
  if (!f.endsWith('.png') || f.startsWith('_')) continue;
  const num = parseInt(f.replace('card_', '').replace('.png', ''), 10);
  if (isNaN(num)) continue;
  const b64 = fs.readFileSync(path.join(CARDS_DIR, f)).toString('base64');
  cards[num] = b64;
}

const keys = Object.keys(cards).map(Number).sort((a, b) => a - b);
let out = '// Auto-generated by scripts/generate_card_data_uris.cjs\n';
out += '// DO NOT EDIT. Base64-encoded card PNGs for offline use.\n\n';
out += 'window.CARD_DATA_URIS = {\n';
for (const num of keys) {
  out += `  ${num}: 'data:image/png;base64,${cards[num]}',\n`;
}
out += '};\n';

fs.writeFileSync(OUT_PATH, out);
console.log(`[generate_card_data_uris] wrote ${keys.length} cards to ${OUT_PATH} (${(fs.statSync(OUT_PATH).size / 1024).toFixed(1)} KB)`);
